services:
  - type: web
    name: quizmania-5bo6
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: "npm start"
    rootDir: server
    envVars:
      - key: HOST 
        value: 0.0.0.0